### ISSUE TITLE
Youtube Shorts Blocker

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [nik132-eng/chrome-extensions#15]
**Is your feature request related to a problem? Please describe.**
I want to add a chrome extension for blocking Youtube Shorts

**Describe the solution you'd like**
The extension will block the shorts and shorts will not be displayed on the youtube - Helps to be more productive

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Swapnil-Singh-99** [comment]
Yah I will be working on it.
Is there any time limit for this?

**Comment by nik132-eng** [comment]
yes better to do it in one week.

**Comment by nik132-eng** [comment]
@Swapnil-Singh-99 
any update on this issue?

**Comment by Swapnil-Singh-99** [comment]
@nik132-eng i have made a pr for roadmap please check

**Comment by nik132-eng** [comment]
unassign @Swapnil-Singh-99  you because of no progress in issues

**Comment by shivang21007** [comment]
@nik132-eng @Swapnil-Singh-99 I would like to work on this issue , Is this contribution count under KWOC23?
