### ISSUE TITLE
Score Viewer

### ISSUE THREAD

**Issue by shivanshsin0203** [nik132-eng/chrome-extensions#18]
**Is your feature request related to a problem? Please describe.**
It is very annoying when you are working on a task or watching something on a certain tab and if you want to check the score of any match you have to go to a new tab search for a match open Crickbuzz or such websites and then watch the score.

**Describe the solution you'd like**
We should plan to build an extension that delivers the match details through data fetching and should show on the top right when clicked—further features like live commentary top sports news live scores etc can be added.

**Comment by Vector-013** [comment]
I would like to work on this issue

**Comment by shivanshsin0203** [comment]
@nik132-eng How should I start with PR

**Comment by nik132-eng** [comment]
Go ahead 👍
