### ISSUE TITLE
Make static site which shows the all chrome extension's description

### ISSUE THREAD

**Issue by nik132-eng** [nik132-eng/chrome-extensions#2]
This issue will open after three or more Chrome extensions are built completely in this Repo

**Comment by Shreyasb1015** [comment]
Please assign me this.

**Comment by nik132-eng** [comment]
> Please assign me this.

https://github.com/nik132-eng/chrome-extensions/issues/2#issue-2007467572

**Comment by Shreyasb1015** [comment]
Should I start working on it ?

**Comment by nik132-eng** [comment]
> Should I start working on it ?

i will reopen it soon
