### ISSUE TITLE
Image Generator Chrome extension

### ISSUE THREAD

**Issue by AaadityaG** [nik132-eng/chrome-extensions#35]
**Is your feature request related to a problem? Please describe.**
While developing the webapp sometimes we need quick and desired image

**Describe the solution you'd like**
Here I can seach for image with the things in it i.e. apple, dog, computer etc.

**Describe alternatives you've considered**
It give the user all desired images

![Capture](https://github.com/nik132-eng/chrome-extensions/assets/114663382/55121c6e-ced1-4fa5-b0f1-e4eb562febca)

**Comment by nik132-eng** [comment]
Make folder 📁 and  make workflow and start your work. Assigning to you.

**Comment by nik132-eng** [comment]
after completing #30 issue will assign it to you

**Comment by AaadityaG** [comment]
I have created a PR already...

**Comment by nik132-eng** [comment]
> I have created a PR already...

your PR needs some changes please review it. after that I will merge it.
https://github.com/nik132-eng/chrome-extensions/pull/32

**Comment by AaadityaG** [comment]
I reviewed it, now please assing this to me...

**Comment by nik132-eng** [comment]
any update on this issue @AaadityaG?

**Comment by AaadityaG** [comment]
Yes I want to do it. Is this project participating in KWoC?
