### ISSUE TITLE
Stock Viewer

### ISSUE THREAD

**Issue by shivanshsin0203** [nik132-eng/chrome-extensions#45]
**Is your feature request related to a problem? Please describe.**
It is quite a headache to go to the website and view today's stock situations currency, bitcoin values, etc.

**Describe the solution you'd like**
I want to build an extension where one can get news of current  INR to dollar values top Stock prices and bitcoin values in just one click

**Comment by nik132-eng** [comment]
as you know about the process go ahead 👍, Create folder and roadmap of your app
